#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration, displays "Hi" on a new line.

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
