#!/usr/bin/env bash
# This script pings an IP address and displays the results.

# Check if an IP address argument is provided
if [ $# -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

# Ping the IP address five times and display the results
ping -c 5 $1
