#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Only the part of the name after the first dash is displayed
current_dir=$(pwd)
files=$(ls -1)
for file in $files
do
name=$(echo $file | cut -d "-" -f 2-)
echo $name
done
