#!/usr/bin/env bash
# This script gives information about the school file
# It checks if the file exists and its characteristics

echo "Checking school file..."
if [ -e school ]
then
echo "school file exists"
if [ -s school ]
then
echo "school file is not empty"
if [ -f school ]
then
echo "school is a regular file"
else
echo "(nothing)"
fi
else
echo "school file is empty"
fi
else
echo "school file does not exist"
fi
