#!/usr/bin/env bash
# Configures an Ubuntu server with the specified IP address changes.

# Create a new hosts file
cp /etc/hosts ~/hosts.new

# Change localhost IP address to 127.0.0.2
echo "127.0.0.2     localhost" > ~/hosts.new

# Change facebook.com IP address to 8.8.8.8
echo "8.8.8.8       facebook.com" >> ~/hosts.new

# Replace the original hosts file with the new one
cp -f ~/hosts.new /etc/hosts
